#!/bin/zsh

local flagConfigFile=$1

processRelativePath logger debug ------------------ new session --------------------

#load silent flag first
if [[ $( cat $flagConfigFile | grep "SILENT_LOG" ) ]] ; then
  export SILENT_LOG=1
fi

while IFS= read -r flag; do
  if [[ -z $flag ]] ; then
    continue 
  fi
  export $flag=1
  processRelativePath logger debug loaded flag : \"$flag\"
done < $flagConfigFile

processRelativePath logger debug loaded flags at : $flagConfigFile
