#!/bin/zsh

debug entered module loader

local modules="$(printRelativePath ../module)"
local modulePrefix="$( printRelativePath ../module/ )"
local enaledModules=$(cat $(printRelativePath ../config/LOAD_MODULE ) | tr '\n' ' ' )
local loadedModule=()
export _dot_dynamic_flags=""
debug enabled modules ${enaledModules[@]}

local loadModule() {
  _failedStatus=0
  local file=$1
  if [[ ! -f $modulePrefix$file ]] ; then 
    _failedStatus=1
    error "Module is mentions but doesn't exist : $file"
    return
  fi
  local header=$( grep " *#!.*" $modulePrefix$file )
  if [[ $header == "#!/bin/bash" ]] || [[ $header == "#!/bin/zsh" ]] ||  [[ $header == "#!/bin/sh" ]] ||  \
    [[ $header == "#!/bin/env bash" ]] || [[ $header == "#!/bin/env zsh" ]] ||  [[ $header == "#!/bin/env sh" ]] ; then
    debug "Loading module : $file"
    resolveDependency $modulePrefix$file
  else 
    _failedStatus=1
    error "Module doesn't have script header ( i.e. #! ) : $file"
  fi
}

local loadDynamicFlags() {
  local script=$1
  local flag="$(grep " *# *f->.*" $script | \
    sed -e "s/ *# *f-> *//g" | \
    tr ' ' '\n' | \
    awk '!/^[[:space:]]*$/')"
  if ! [[ -z $flag ]] ; then
    _dot_dynamic_flags+=$flag
    _dot_dynamic_flags+="\n"
  fi
}

local resolveDependency() {
  local script=$1
  if [[ "${loadedModule[@]}" =~ ".*$script.*" ]] ; then 
    debug "Duplicate module entry or requested by other module ${script#$modulePrefix}" 
    return
  fi
  loadedModule+=($script)
  grep " *# *d->.*" $script | tr '\n' ',' | xargs echo | sed -e 's/#->//g' \
    | while read -r -d ',' module; do
    module="${module// /}"
    debug "Loading module as dependency $module" 
    loadModule $module
    if [[ $_failedStatus == 1 ]] ; then
      unset _failedStatus
      error "Failed to load module ${script#$modulePrefix} depends on $module"
      return
    fi
    unset _failedStatus
  done 
  loadDynamicFlags $script
  if [[ -v SILENT_MODULE_LOAD ]] ; then
    if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
      source $script > /dev/null 2>&1 
    else
      source $script > /dev/null
    fi
  else
    if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
      source $script 2>&1
    else
      source $script
    fi
  fi
  debug "Loaded module ${script#$modulePrefix}" 
}

processAndAssignPriority() {
  awk '!/^[[:space:]]*$/' | \
  awk "BEGIN { i=0; count=\"$priority_count_starter\" ; if ( count == \"\" ) { count=50 }  }  \
  { \
    if ( \$1 == \"?\" ) { \
      unnamed[i++] = \$2   \
    } else { \
      savedNum[\$2] = \$1 ; \
      occupied[\$1] = \$2  ;\
      if ( (count+0) > (\$1+0) ) { \
        count = \$1
      }\
    }
  } \
  END { \
    for ( module in unnamed ) {\
      while ( occupied[count] ) {\
        used[occupied[count]] = 1 ; \
        printf \"%d %s\\n\" , count , occupied[count++] \
      } ; \
      printf \"%d %s\\n\" , count++ , unnamed[module] \
    }\
  }\
  END {\
    idx = 0;\
    for ( prio in occupied ) {\
      mod = occupied[prio];\
      if ( !used[mod] && mod != \"\" ) {\
        pending[idx++] = prio + 0; \
      }\
    }\
    for ( i = 0; i < idx; i++ ) {\
      for ( j = 0; j < idx - i - 1; j++ ) {\
        if ( pending[j] > pending[j + 1] ) {\
          temp = pending[j];\
          pending[j] = pending[j + 1];\
          pending[j + 1] = temp;\
        }\
      }\
    }\
    for ( i = 0; i < idx; i++ ) {\
      true_prio = pending[i];\
      printf \"%d %s\n\", true_prio, occupied[true_prio];\
    }\
  }"
}

# priority module-name
local orderedList=""
# create priority list
while IFS= read -r module <&3; do 
  local priority="$( \
    grep " *# *p-> *-\?[0-9]*" "${_dot_files_root_dir}module/$module" | \
    sed -e "s/ *# *p-> *//g" | \
    awk 'BEGIN { max = $1 } { if ( max < $1 ) { max = $1 } } END { print max }'
  )"
  if [[ $priority == "" ]] ; then 
    priority="?"
  fi
  orderedList+="$priority $module\n"
done 3< "${_dot_files_root_dir}config/LOAD_MODULE"

debug \[Moduleloader\] preprocess order $orderedList
orderedList="$( echo $orderedList | processAndAssignPriority )"
unset processAndAssignPriority
debug \[Moduleloader\] postprocessed order $orderedList

for module in ${(f)orderedList}; do
  loadModule "$( echo $module | awk '{ print $2 }' )"
done
